from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AppMainWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.setFixedSize(1200, 675)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1200, 675))
        self.label_2.setStyleSheet("background-color: white;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 241, 675))
        self.label_3.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(10, 15, 211, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(0, 325, 241, 1))
        self.label_5.setStyleSheet("background-color: grey;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(10, 90, 161, 20))
        self.label_6.setObjectName("label_6")
        self.SelectUrType = QtWidgets.QComboBox(parent=Form)
        self.SelectUrType.setGeometry(QtCore.QRect(10, 120, 221, 22))
        self.SelectUrType.setObjectName("SelectUrType")
        self.SelectUrType.addItem("")
        self.SelectUrType.addItem("")
        self.SelectUrType.addItem("")
        self.SelectUrType.addItem("")
        self.SelectUrType.addItem("")
        self.SelectUrType.addItem("")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(10, 45, 201, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=Form)
        self.label_8.setGeometry(QtCore.QRect(10, 190, 221, 31))
        self.label_8.setObjectName("label_8")
        self.EasyUrButton = QtWidgets.QPushButton(parent=Form)
        self.EasyUrButton.setGeometry(QtCore.QRect(10, 220, 221, 23))
        self.EasyUrButton.setObjectName("EasyUrButton")
        self.MidUrButton = QtWidgets.QPushButton(parent=Form)
        self.MidUrButton.setGeometry(QtCore.QRect(10, 250, 221, 23))
        self.MidUrButton.setObjectName("MidUrButton")
        self.HardUrButton = QtWidgets.QPushButton(parent=Form)
        self.HardUrButton.setGeometry(QtCore.QRect(10, 280, 221, 23))
        self.HardUrButton.setObjectName("HardUrButton")
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setGeometry(QtCore.QRect(0, 76, 241, 1))
        self.label_9.setStyleSheet("background-color: grey;")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(parent=Form)
        self.label_12.setGeometry(QtCore.QRect(241, 0, 959, 76))
        self.label_12.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.ExitButton = QtWidgets.QPushButton(parent=Form)
        self.ExitButton.setGeometry(QtCore.QRect(1110, 20, 75, 36))
        self.ExitButton.setStyleSheet("background-color: rgb(40, 167, 234); border-radius: 3px; font-size: 13px; font: Verdana")
        self.ExitButton.setObjectName("ExitButton")
        self.profileButton = QtWidgets.QPushButton(parent=Form)
        self.profileButton.setGeometry(QtCore.QRect(1030, 20, 75, 36))
        self.profileButton.setStyleSheet("background-color: rgb(40, 167, 234); border-radius: 3px; font-size: 13px; font: Verdana")
        self.profileButton.setObjectName("profileButton")
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.SelectUrType.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.EasyUrButton.raise_()
        self.MidUrButton.raise_()
        self.HardUrButton.raise_()
        self.label_9.raise_()
        self.label_12.raise_()
        self.ExitButton.raise_()
        self.profileButton.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Algebrator"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Algebrator</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline; color:#ffffff;\">Уравнения</span></p></body></html>"))
        self.SelectUrType.setItemText(0, _translate("Form", "Рациональные"))
        self.SelectUrType.setItemText(1, _translate("Form", "Иррациональные"))
        self.SelectUrType.setItemText(2, _translate("Form", "Модульные"))
        self.SelectUrType.setItemText(3, _translate("Form", "Показательные"))
        self.SelectUrType.setItemText(4, _translate("Form", "Логарифмические"))
        self.SelectUrType.setItemText(5, _translate("Form", "Тригонометрические"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Профильная математика</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Решать задания:</span></p></body></html>"))
        self.EasyUrButton.setText(_translate("Form", "Простые"))
        self.MidUrButton.setText(_translate("Form", "Средние"))
        self.HardUrButton.setText(_translate("Form", "Сложные"))
        self.ExitButton.setText(_translate("Form", "Выйти"))
        self.profileButton.setText(_translate("Form", "Профиль"))
