from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Profile(object):
    def setupUi(self, Form):
        Form.setObjectName("Algebrator")
        Form.setFixedSize(873, 605)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 881, 611))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 881, 71))
        self.label_2.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.nick_label = QtWidgets.QLabel(parent=Form)
        self.nick_label.setGeometry(QtCore.QRect(20, 20, 301, 31))
        self.nick_label.setObjectName("nick_label")
        self.updateButton = QtWidgets.QPushButton(parent=Form)
        self.updateButton.setGeometry(QtCore.QRect(780, 17, 75, 36))
        self.updateButton.setStyleSheet("background-color: rgb(40, 167, 234); border-radius: 3px; font-size: 13px;")
        self.updateButton.setObjectName("updateButton")
        self.image_label = QtWidgets.QLabel(parent=Form)
        self.image_label.setGeometry(QtCore.QRect(20, 120, 561, 451))
        self.image_label.setStyleSheet("")
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.rac_label = QtWidgets.QLabel(parent=Form)
        self.rac_label.setGeometry(QtCore.QRect(600, 140, 281, 21))
        self.rac_label.setObjectName("rac_label")
        self.irr_label = QtWidgets.QLabel(parent=Form)
        self.irr_label.setGeometry(QtCore.QRect(600, 190, 281, 21))
        self.irr_label.setObjectName("irr_label")
        self.mod_label = QtWidgets.QLabel(parent=Form)
        self.mod_label.setGeometry(QtCore.QRect(600, 240, 281, 21))
        self.mod_label.setObjectName("mod_label")
        self.poc_label = QtWidgets.QLabel(parent=Form)
        self.poc_label.setGeometry(QtCore.QRect(600, 290, 281, 21))
        self.poc_label.setObjectName("poc_label")
        self.log_label = QtWidgets.QLabel(parent=Form)
        self.log_label.setGeometry(QtCore.QRect(600, 340, 281, 21))
        self.log_label.setObjectName("log_label")
        self.trg_label = QtWidgets.QLabel(parent=Form)
        self.trg_label.setGeometry(QtCore.QRect(600, 390, 281, 21))
        self.trg_label.setObjectName("trg_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Algebrator"))
        self.nick_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">your_nick</span></p></body></html>"))
        self.updateButton.setText(_translate("Form", "Обновить"))
        self.rac_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Рациональные: Решено</span></p></body></html>"))
        self.irr_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Иррациональные: Решено</span></p></body></html>"))
        self.mod_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Модульные: Решено</span></p></body></html>"))
        self.poc_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Показательные: Решено</span></p></body></html>"))
        self.log_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Логарифмические: Решено</span></p></body></html>"))
        self.trg_label.setText(_translate("Form","<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Тригонометрические: Решено</span></p></body></html>"))
